services:
  web_app:
    build: ./packages/web/ 
    ports:
      - 3000:3000
    networks:
      - internal

  server_app:
    build: ./packages/server/
    ports:
      - 2000:2000
    networks:
      - internal

#   redis: 
#     image: redis:alpine
#     volumes:
#       - redis:/data
#     networks:
#       - internal
#     ports:
#       - 6379:6379

# volumes:
#   redis:

networks:
  internal:
    name: wind-im-internal