-- AlterTable
ALTER TABLE "Message" ADD COLUMN "privateMsgId" INTEGER;

-- CreateTable
CREATE TABLE "PrivateMsg" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "fromUid" INTEGER NOT NULL,
    "toUid" INTEGER NOT NULL,
    "status" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PrivateMsg_fromUid_fkey" FOREIGN KEY ("fromUid") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PrivateMsg_toUid_fkey" FOREIGN KEY ("toUid") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
